---
- name: copy service file
  become: true
  template:
    src: aleo.service.j2
    dest: "{{ aleo_service_path }}"
    owner: root
    group: root
    mode: "0644"

- name: verify aleo.service file exists
  stat:
    path: "{{ aleo_service_path }}"
  register: aleo_service

- name: fail if aleo.service file was not created
  fail:
    msg: "aleo.service file was not created successfully!"
  when: not aleo_service.stat.exists

- name: start service
  become: true
  systemd:
    name: aleo.service
    state: restarted
    daemon_reload: true
    enabled: true